version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: tender-web-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/etc/nginx/www